/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrimeritObrazRouteImport } from './routes/primerit-obraz'
import { Route as TestVolosRouteImport } from './routes/test-volos'
import { Route as UhodRouteImport } from './routes/uhod'
import { Route as UslugiRouteImport } from './routes/uslugi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeritObrazRoute = PrimeritObrazRouteImport.update({
  id: '/primerit-obraz',
  path: '/primerit-obraz',
  getParentRoute: () => rootRouteImport,
} as any)
const TestVolosRoute = TestVolosRouteImport.update({
  id: '/test-volos',
  path: '/test-volos',
  getParentRoute: () => rootRouteImport,
} as any)
const UhodRoute = UhodRouteImport.update({
  id: '/uhod',
  path: '/uhod',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/primerit-obraz': typeof PrimeritObrazRoute
  '/test-volos': typeof TestVolosRoute
  '/uhod': typeof UhodRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/primerit-obraz': typeof PrimeritObrazRoute
  '/test-volos': typeof TestVolosRoute
  '/uhod': typeof UhodRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/primerit-obraz': typeof PrimeritObrazRoute
  '/test-volos': typeof TestVolosRoute
  '/uhod': typeof UhodRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/primerit-obraz'
    | '/test-volos'
    | '/uhod'
    | '/uslugi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/primerit-obraz'
    | '/test-volos'
    | '/uhod'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/primerit-obraz'
    | '/test-volos'
    | '/uhod'
    | '/uslugi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktyRoute: typeof KontaktyRoute
  PortfolioRoute: typeof PortfolioRoute
  PrimeritObrazRoute: typeof PrimeritObrazRoute
  TestVolosRoute: typeof TestVolosRoute
  UhodRoute: typeof UhodRoute
  UslugiRoute: typeof UslugiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primerit-obraz': {
      id: '/primerit-obraz'
      path: '/primerit-obraz'
      fullPath: '/primerit-obraz'
      preLoaderRoute: typeof PrimeritObrazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-volos': {
      id: '/test-volos'
      path: '/test-volos'
      fullPath: '/test-volos'
      preLoaderRoute: typeof TestVolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uhod': {
      id: '/uhod'
      path: '/uhod'
      fullPath: '/uhod'
      preLoaderRoute: typeof UhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktyRoute: KontaktyRoute,
  PortfolioRoute: PortfolioRoute,
  PrimeritObrazRoute: PrimeritObrazRoute,
  TestVolosRoute: TestVolosRoute,
  UhodRoute: UhodRoute,
  UslugiRoute: UslugiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
